/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    AdminAbout: typeof import('./src/components/admin/AdminAbout.vue')['default']
    AdminAccount: typeof import('./src/components/admin/AdminAccount.vue')['default']
    AdminContact: typeof import('./src/components/admin/AdminContact.vue')['default']
    AdminHardskills: typeof import('./src/components/admin/AdminHardskills.vue')['default']
    AdminHome: typeof import('./src/components/admin/AdminHome.vue')['default']
    AdminProjects: typeof import('./src/components/admin/AdminProjects.vue')['default']
    AdminProjectSingle: typeof import('./src/components/admin/AdminProjectSingle.vue')['default']
    AdminSideNav: typeof import('./src/components/admin/AdminSideNav.vue')['default']
    AdminTags: typeof import('./src/components/admin/AdminTags.vue')['default']
    AlertMessage: typeof import('./src/components/AlertMessage.vue')['default']
    ContactMe: typeof import('./src/components/ContactMe.vue')['default']
    HardskillBox: typeof import('./src/components/HardskillBox.vue')['default']
    HardSkillCardSingle: typeof import('./src/components/HardSkillCardSingle.vue')['default']
    HardskillsCards: typeof import('./src/components/HardskillsCards.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    HeroCall: typeof import('./src/components/HeroCall.vue')['default']
    ProjectCardSingle: typeof import('./src/components/ProjectCardSingle.vue')['default']
    ProjectModal: typeof import('./src/components/ProjectModal.vue')['default']
    ProjectsCards: typeof import('./src/components/ProjectsCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    TagBox: typeof import('./src/components/TagBox.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    UTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
